"""Frozen treaty types shared by every layer: verifier, policy, rail, ledger, eval, api.

Do not edit this file without explicit approval — every downstream module depends
on these shapes. All money is integer paise. Never float, never rupees.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Literal, Optional

from pydantic import BaseModel, Field, model_validator


class ActionType(str, Enum):
    CREATE_ORDER = "create_order"
    CAPTURE = "capture"
    REFUND = "refund"


class Window(str, Enum):
    DAY = "day"
    MONTH = "month"


class Verdict(str, Enum):
    SAFE = "safe"
    VIOLATION = "violation"
    ERROR = "error"


class LedgerDecision(str, Enum):
    ALLOW = "allow"
    BLOCK = "block"
    GENESIS = "genesis"


class PolicyIR(BaseModel):
    """Typed policy compiled deterministically to Z3 constraints in Phase 2.

    Covers, and only covers, the fields in MASTER.md section 2. Resist adding more.
    """

    per_txn_cap_paise: Optional[int] = Field(default=None, ge=0)
    window_cap_paise: Optional[int] = Field(default=None, ge=0)
    window: Optional[Window] = None
    allowed_categories: Optional[list[str]] = None
    blocked_categories: list[str] = Field(default_factory=list)
    max_txn_count: Optional[int] = Field(default=None, ge=0)
    refund_bounded_by_capture: Literal[True] = True
    require_human_above_paise: Optional[int] = Field(default=None, ge=0)

    @model_validator(mode="after")
    def _monthly_cap_not_below_per_txn_cap(self) -> "PolicyIR":
        if (
            self.window == Window.MONTH
            and self.window_cap_paise is not None
            and self.per_txn_cap_paise is not None
            and self.window_cap_paise < self.per_txn_cap_paise
        ):
            raise ValueError(
                "window_cap_paise cannot be lower than per_txn_cap_paise "
                "when window is 'month'"
            )
        return self


class Mandate(BaseModel):
    """AP2-shaped spending mandate: a merchant's natural-language authorization
    paired with the typed policy it was compiled to. Hand-modeled, not the AP2 SDK.
    """

    mandate_id: str
    principal_id: str
    agent_id: str
    natural_language_text: str
    policy: PolicyIR
    issued_at: datetime
    expires_at: Optional[datetime] = None


class Action(BaseModel):
    """A single proposed or executed payment action."""

    action_id: str
    action_type: ActionType
    order_id: str
    amount_paise: int = Field(gt=0)
    category: Optional[str] = None
    occurred_at: datetime


class CounterexampleStep(BaseModel):
    step_index: int
    action_type: ActionType
    order_id: str
    amount_paise: int
    category: Optional[str] = None


class Counterexample(BaseModel):
    """A readable trace of every step up to and including the violation."""

    violated_property: str
    trace: list[CounterexampleStep]
    violation_step_index: int
    explanation: Optional[str] = None


class VerificationResult(BaseModel):
    verdict: Verdict
    properties_checked: list[str]
    horizon: int
    counterexample: Optional[Counterexample] = None
    latency_ms: float
    error_message: Optional[str] = None


class LedgerEntry(BaseModel):
    """One entry in the hash-chained, Ed25519-signed audit ledger."""

    index: int
    entry_id: str
    timestamp: datetime
    decision: LedgerDecision
    action: Optional[Action] = None
    verification_result: Optional[VerificationResult] = None
    razorpay_payment_id: Optional[str] = None
    prev_hash: str
    entry_hash: str
    signature: str
